# Generated by Django 4.0.5 on 2022-07-07 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('statement', models.TextField()),
                ('difficulty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('curr_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
        migrations.CreateModel(
            name='solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.TextField(default='WA')),
                ('time_of_submit', models.DateTimeField(auto_now=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('curr_problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='judge.problem')),
            ],
        ),
    ]
