# Generated by Django 4.0.5 on 2022-07-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0002_alter_solution_curr_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='curr_problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judge.problem'),
        ),
    ]
